In [82]:
import torch
import numpy as np

In [83]:
torch.cuda.is_available()

True

In [84]:
import numpy

In [85]:
print("hello")

hello


In [86]:
a=torch.tensor(1.)


In [87]:
a.type()

'torch.FloatTensor'

In [88]:
af=torch.tensor(1.3)
#a.type()

In [89]:
aint=torch.tensor(1)
#a.type()

In [90]:
aint1d=torch.tensor([1])
a.type()

'torch.FloatTensor'

In [91]:
af.shape

torch.Size([])

In [92]:
aint1d.shape

torch.Size([1])

In [93]:
torch.FloatTensor(1)

tensor([0.])

In [94]:
torch.FloatTensor(2,2)

tensor([[0.0000e+00, 1.0010e-38],
        [1.5695e-43, 4.5909e-41]])

In [95]:
data=np.ones(3)

In [96]:
data=torch.from_numpy(data)

In [97]:
isinstance(data,torch.DoubleTensor)

True

In [98]:
torch.__version__

'1.13.0'

In [99]:
a=torch.rand(2,3,4,5)
a

tensor([[[[0.7112, 0.0248, 0.5733, 0.5413, 0.5492],
          [0.5687, 0.6248, 0.0085, 0.7314, 0.0200],
          [0.3079, 0.9239, 0.8813, 0.7154, 0.6942],
          [0.9502, 0.5270, 0.6511, 0.2206, 0.8418]],

         [[0.6448, 0.9899, 0.0493, 0.5478, 0.8221],
          [0.8761, 0.2961, 0.6342, 0.8113, 0.0665],
          [0.7153, 0.3752, 0.9047, 0.9096, 0.3869],
          [0.1666, 0.2427, 0.9653, 0.6167, 0.9346]],

         [[0.1006, 0.6248, 0.2751, 0.2998, 0.0758],
          [0.9294, 0.3181, 0.2673, 0.1601, 0.9255],
          [0.8039, 0.8013, 0.3860, 0.3713, 0.5360],
          [0.6038, 0.9031, 0.3450, 0.9960, 0.3888]]],


        [[[0.5472, 0.2931, 0.7985, 0.2799, 0.4096],
          [0.5840, 0.7494, 0.7817, 0.6928, 0.9048],
          [0.0445, 0.2644, 0.2395, 0.9452, 0.1636],
          [0.0553, 0.5951, 0.0925, 0.0827, 0.9109]],

         [[0.7898, 0.9365, 0.4080, 0.9648, 0.9008],
          [0.9100, 0.0159, 0.4776, 0.7994, 0.1717],
          [0.0603, 0.1396, 0.8510, 0.0938, 0.1166],
  

In [100]:
a.size()

torch.Size([2, 3, 4, 5])

In [101]:
a.dim()

4

In [102]:
a.numel()

120

In [103]:
a=torch.tensor(1)
a.dim()

0

# 创建tensor


In [104]:
a=np.array([2,3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [105]:
a=np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [106]:
a=torch.tensor([2,3])
a

tensor([2, 3])

In [107]:
a=torch.Tensor(2,3)
a

tensor([[4.3008e-05, 1.7079e-07, 8.3897e-07],
        [2.1037e+23, 1.0385e+21, 6.6349e-10]])

In [108]:
a=torch.Tensor([2,3])
a

tensor([2., 3.])

In [109]:
torch.full([10],0)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [111]:
idx=torch.randperm(10)

In [112]:
idx

tensor([0, 2, 6, 4, 5, 7, 8, 1, 3, 9])

In [113]:
idx

tensor([0, 2, 6, 4, 5, 7, 8, 1, 3, 9])

In [114]:
idx

tensor([0, 2, 6, 4, 5, 7, 8, 1, 3, 9])

In [115]:
idx

tensor([0, 2, 6, 4, 5, 7, 8, 1, 3, 9])

In [116]:
a=torch.rand(4,3,28,28)#假设这是四张RGB的28*28的方形图片

In [117]:
a.unsqueeze(0).shape

torch.Size([1, 4, 3, 28, 28])

In [118]:
b=torch.rand(32)
f=torch.rand(4,32,14,14)
b=b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

In [119]:
a=torch.rand(1,3,4)
print(a.shape)
a.squeeze(1).shape


torch.Size([1, 3, 4])


torch.Size([1, 3, 4])

In [120]:
a=torch.rand(2,3,4,5)
#a.transpose(0,2).shape

In [121]:
a1=a.transpose(1,3)
#print(a1)
a2=a1.contiguous()
#print("contiguous",a1)
print(a2.eq(a1))
a2.view(2,3*4*5)


tensor([[[[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]]],


        [[[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True,

tensor([[0.6312, 0.9933, 0.5377, 0.7318, 0.2078, 0.9710, 0.4384, 0.3013, 0.0733,
         0.5086, 0.9573, 0.8278, 0.1410, 0.1290, 0.8233, 0.3483, 0.9665, 0.1124,
         0.1324, 0.2083, 0.3420, 0.0353, 0.5046, 0.7499, 0.1562, 0.0253, 0.9208,
         0.8289, 0.7581, 0.4521, 0.0626, 0.6262, 0.6359, 0.0854, 0.2416, 0.4477,
         0.2993, 0.3170, 0.3876, 0.7347, 0.1205, 0.7537, 0.9399, 0.8445, 0.7295,
         0.8310, 0.9431, 0.7039, 0.7438, 0.5922, 0.7551, 0.6958, 0.8935, 0.8494,
         0.3067, 0.1384, 0.8347, 0.4362, 0.7398, 0.2751],
        [0.7544, 0.6912, 0.2899, 0.0675, 0.4738, 0.6393, 0.6752, 0.9511, 0.0607,
         0.6325, 0.1654, 0.3859, 0.2195, 0.0139, 0.7961, 0.2172, 0.5905, 0.1229,
         0.8499, 0.8049, 0.1966, 0.4302, 0.7685, 0.4149, 0.2150, 0.0075, 0.1604,
         0.2073, 0.9286, 0.6231, 0.3585, 0.1113, 0.4701, 0.3159, 0.1484, 0.1120,
         0.1801, 0.0055, 0.5385, 0.1938, 0.3794, 0.9657, 0.6594, 0.9705, 0.6964,
         0.8507, 0.7202, 0.4779, 0.4101, 0.5388, 0.

In [122]:
img1=torch.ones(2,3,4,5)
print(img1)

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [123]:
bis=torch.tensor([0.5242,0.4444,0.3333,0.22222,0.11111])
img1=img1+bis
print(img1)

tensor([[[[1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111]],

         [[1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111]],

         [[1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111]]],


        [[[1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111]],

         [[1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
          [1.5242, 1.4444, 1.3333, 1.2222, 1.1111],
  

In [124]:
a=torch.tensor([[0],[10],[20],[30]])
b=torch.tensor([0,1,2])
c=a+b
print(c)

tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])


In [125]:
a1=torch.rand(4,3,32,32)
a2=torch.rand(5,3,32,32)
torch.cat([a1,a2],dim=0).shape#从第0个维度将a1和a2两个tensor进行拼接
#out:torch.Size([9, 3, 32, 32])

torch.Size([9, 3, 32, 32])

In [126]:
a1=torch.ones(4,3,32,32)
a2=torch.zeros(4,3,32,32)
torch.stack([a1,a2],dim=2).shape#在第2维度处创建一个新的维度，将a1和a2在的第2维度进行堆叠，即[:,:,0,...]就是a1全为1，[:,:,1,...]则为a2全为0
#a3[:,:,1,...]

torch.Size([4, 3, 2, 32, 32])

In [127]:
a1=torch.ones(4,3)
a2=torch.zeros(4,3)
torch.stack([a1,a2],dim=0).shape

torch.Size([2, 4, 3])

In [128]:
a3=torch.eye(4,3)
a=torch.stack([a1,a2,a3],dim=0)

b1,b2,b3=a.split(1,dim=0)
# print(b1)
# print(b2)
# print(b3)

b1,b2,b3=a.chunk(3,dim=0)
print(b1),print(b2),print(b3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [0., 0., 0.]]])


(None, None, None)

In [129]:
a=torch.rand(3,4)
b=torch.rand(4)
c=a+b
c.shape
#out: [3,4]
torch.all(torch.eq(a+b,torch.add(a,b)))
torch.all(torch.eq(a-b,torch.sub(a,b)))
torch.all(torch.eq(a*b,torch.mul(a,b)))
torch.all(torch.eq(a/b,torch.div(a,b)))


tensor(True)

In [130]:
a=torch.ones(2,2)
b=a*3
a@b

tensor([[6., 6.],
        [6., 6.]])

In [131]:
a=torch.rand(4,3,28,64)
b=torch.rand(4,1,64,32)
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [132]:
a=torch.full([2,2],3)
a.pow(2)

tensor([[9, 9],
        [9, 9]])

In [133]:
a=torch.exp(torch.ones(2,2))
torch.log2(a)

tensor([[1.4427, 1.4427],
        [1.4427, 1.4427]])

In [134]:
a=torch.tensor(3.14)
a.floor(),a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [135]:
grad=torch.rand(2,3)*15
print(grad)
# grad.max()
# grad.median()
# grad.clamp(10)
grad.clamp(0,10)

tensor([[ 3.7864,  5.7644,  8.5572],
        [ 6.7648, 14.7264,  7.2083]])


tensor([[ 3.7864,  5.7644,  8.5572],
        [ 6.7648, 10.0000,  7.2083]])

In [136]:
a=torch.full([8],1.)#8个1的向量
b=a.view(2,4)
c=a.view(2,2,2)
print(b)
a.norm(1),b.norm(1),c.norm(1) #1范数，就是所有矩阵元素绝对值的和，所以全输出8

a.norm(2),b.norm(2),c.norm(2) #2范数，就是所有矩阵元素的绝对值的平方和开根号，所以全输出 根号8 =2.82

b.norm(1,dim=1)#对第1维度的1范数
b.norm(2,dim=1)#对第1维度的2范数

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([2., 2.])

In [137]:
a=torch.arange(8).view(2,4).float()*2
a.min(),a.max(),a.mean(),a.prod(),a.sum()# 最小值、最大值、平均值和累乘值（因为有0所以是0）还有求和


(tensor(0.), tensor(14.), tensor(7.), tensor(0.), tensor(56.))

In [138]:
a.argmax(),a.argmin()
a.argmax(dim=1),a.argmin(dim=1)

(tensor([3, 3]), tensor([0, 0]))

In [139]:
a=torch.rand(3,3,4)
print(a)
a.argmax(dim=2)

tensor([[[0.8042, 0.2046, 0.0155, 0.0173],
         [0.8587, 0.9446, 0.8441, 0.8173],
         [0.0341, 0.1659, 0.4175, 0.5821]],

        [[0.8190, 0.1308, 0.9884, 0.4505],
         [0.8856, 0.5809, 0.8452, 0.1877],
         [0.2887, 0.6354, 0.5857, 0.7234]],

        [[0.8085, 0.6717, 0.2831, 0.1998],
         [0.0333, 0.4126, 0.7528, 0.7036],
         [0.0595, 0.7773, 0.7674, 0.0981]]])


tensor([[0, 1, 3],
        [2, 0, 3],
        [0, 2, 1]])

In [140]:
a=torch.rand(4,10)
print(a.max(dim=1))
print(a.max(dim=1,keepdim=True))

torch.return_types.max(
values=tensor([0.9437, 0.8481, 0.9842, 0.9469]),
indices=tensor([9, 3, 9, 2]))
torch.return_types.max(
values=tensor([[0.9437],
        [0.8481],
        [0.9842],
        [0.9469]]),
indices=tensor([[9],
        [3],
        [9],
        [2]]))


In [141]:
a=torch.rand(4,10)
a.topk(5,dim=1)

torch.return_types.topk(
values=tensor([[0.8650, 0.8603, 0.8522, 0.7385, 0.6588],
        [0.9116, 0.8802, 0.5688, 0.5148, 0.5053],
        [0.9437, 0.8801, 0.8243, 0.6371, 0.5949],
        [0.9504, 0.9059, 0.9051, 0.6418, 0.5841]]),
indices=tensor([[4, 2, 7, 3, 9],
        [0, 9, 6, 5, 3],
        [2, 1, 7, 6, 8],
        [4, 5, 7, 2, 1]]))

In [142]:
a=torch.rand(4,4)
b=a>0.5
b.type()

'torch.BoolTensor'

In [143]:
a=torch.rand(4,4)
print(a)
a0=torch.zeros(4,4)
a1=torch.ones(4,4)
torch.where(a>0.5,a1,a0)#a满足条件取a1中的值，不满足条件取a2中的值


tensor([[0.7952, 0.7491, 0.1997, 0.8538],
        [0.4975, 0.0360, 0.0316, 0.8115],
        [0.3345, 0.9763, 0.9498, 0.9617],
        [0.5783, 0.6743, 0.6499, 0.7716]])


tensor([[1., 1., 0., 1.],
        [0., 0., 0., 1.],
        [0., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [144]:
a=torch.rand(4,10)
idx=a.topk(dim=1,k=3)
idx=idx[1]
print(idx)
label=torch.arange(10)+33
label=label.expand(4,10)
print(label)
torch.gather(label,dim=1,index=idx.long())

tensor([[1, 0, 6],
        [4, 3, 2],
        [2, 5, 7],
        [5, 4, 2]])
tensor([[33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
        [33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
        [33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
        [33, 34, 35, 36, 37, 38, 39, 40, 41, 42]])


tensor([[34, 33, 39],
        [37, 36, 35],
        [35, 38, 40],
        [38, 37, 35]])

In [145]:
import torch.nn.functional as F


In [150]:
#下面要对y=xw这个函数进行回归运算，
x=torch.ones(1)
w=torch.full([1],2.)
print("x=",x)
print("w=",w)
mse=F.mse_loss(torch.ones(1),x*w)
print("MSE=",mse)
# torch.autograd.grad(mse,[w])
w.requires_grad_()
mse=F.mse_loss(torch.ones(1),x*w)
torch.autograd.grad(mse,[w])

x= tensor([1.])
w= tensor([2.])
MSE= tensor(1.)


(tensor([2.]),)